USE [master]
GO

/****** Object:  Database [QLTrungTamAnhNguEspeed]    Script Date: 26-Apr-17 10:56:09 PM ******/
CREATE DATABASE [QLTrungTamAnhNguEspeed]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLTrungTamAnhNguEspeed', FILENAME = N'D:\Program\SQL\MSSQL13.SQLEXPRESS\MSSQL\DATA\QLTrungTamAnhNguEspeed.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLTrungTamAnhNguEspeed_log', FILENAME = N'D:\Program\SQL\MSSQL13.SQLEXPRESS\MSSQL\DATA\QLTrungTamAnhNguEspeed_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLTrungTamAnhNguEspeed].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET RECOVERY FULL 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET  MULTI_USER 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET QUERY_STORE = OFF
GO

USE [QLTrungTamAnhNguEspeed]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [QLTrungTamAnhNguEspeed] SET  READ_WRITE 
GO


